CREATE VIEW per36min AS
SELECT  name, year, teamID, pos, G, GS, MP,
      FG,
      FGA,
      FG%,
      3P,
      3PA,
      3P%,
      2P,
      2PA,
      2P%,
      FT,
      FTA,
      FT% ,
      ORB,
      DRB,
      TRB,
      AST,
      STL,
      BLK,
      TOV,
      PF,
      PTS
FROM PlayerStats;

UPDATE per36min
SET FG = FG/(MP/36),
      FGA = FGA/(MP/36),
      FG% = FG%/(MP/36),
      3P = 3P/(MP/36),
      3PA = 3PA/(MP/36),
      3P% = 3P%/(MP/36),
      2P = 2P/(MP/36),
      2PA = 2PA/(MP/36),
      2P% = 2P%/(MP/36),
      FT = FT/(MP/36),
      FTA = FTA/(MP/36),
      FT% = FT%/(MP/36),
      ORB = ORB(MP/36),
      DRB = DRB/(MP/36),
      TRB = TRB/(MP/36),
      AST = AST/(MP/36),
      STL = STL/(MP/36),
      BLK = BLK/(MP/36),
      TOV = TOV/(MP/36),
      PF = PF/(MP/36),
      PTS = PTS/(MP/36);

create view per100poss as
SELECT  name, year, teamID, pos, G, GS, MP,
      FG,
      FGA,
      FG%,
      3P,
      3PA,
      3P%,
      2P,
      2PA,
      2P%,
      FT,
      FTA,
      FT% ,
      ORB,
      DRB,
      TRB,
      AST,
      STL,
      BLK,
      TOV,
      PF,
      PTS
FROM PlayerStats;

UPDATE per100poss
SET FG = FG/(MP/36),
      FGA = FGA/(MP/36),
      FG% = FG%/(MP/36),
      3P = 3P/(MP/36),
      3PA = 3PA/(MP/36),
      3P% = 3P%/(MP/36),
      2P = 2P/(MP/36),
      2PA = 2PA/(MP/36),
      2P% = 2P%/(MP/36),
      FT = FT/(MP/36),
      FTA = FTA/(MP/36),
      FT% = FT%/(MP/36),
      ORB = ORB(MP/36),
      DRB = DRB/(MP/36),
      TRB = TRB/(MP/36),
      AST = AST/(MP/36),
      STL = STL/(MP/36),
      BLK = BLK/(MP/36),
      TOV = TOV/(MP/36),
      PF = PF/(MP/36),
      PTS = PTS/(MP/36);
