CREATE TABLE Player
  (
     name VARCHAR(50) NOT NULL PRIMARY KEY,
     height INT,
     weight INT,
     collage VARCHAR(50),
     birthCity VARCHAR(50),
     birthState VARCHAR(50),
     born INT,
  );

  CREATE TABLE PlayerStats (
      name VARCHAR(50) NOT NULL,
      year INT NOT NULL,
      teamID INT NOT NULL,
      PRIMARY KEY(name, year, teamID),
      pos VARCHAR(50),
      age INT,
      Tm VARCHAR(3),
      G INT,
      GS INT,
      MP INT,
      PER INT,
      TS% INT,
      3PAr INT,
      FTr INT,
      ORB% INT,
      DRB% INT,
      TRB% INT,
      AST% INT,
      STL% INT,
      BLK% INT,
      TOV% INT,
      USG% INT,
      blanl INT,
      OWS INT,
      DWS INT,
      WS INT,
      WS/48 INT,
      blank2 INT,
      OBPM INT,
      DBPM INT,
      BPM INT,
      VORP INT,
      FG INT,
      FGA INT,
      FG% INT,
      3P INT,
      3PA INT,
      3P% INT,
      2P INT,
      2PA INT,
      2P% INT,
      eFG% INT,
      FT INT,
      FTA INT,
      FT% INT,
      ORB INT,
      DRB INT,
      TRB INT,
      AST INT,
      STL INT,
      BLK INT,
      TOV INT,
      PF INT,
      PTS INT
  );

