CREATE TABLE Player
  (
     name VARCHAR(50) NOT NULL PRIMARY KEY,
     height INT,
     weight INT,
     collage VARCHAR(50),
     born INT,
     birthCity VARCHAR(50),
     birthState VARCHAR(50)
  );

  CREATE TABLE PlayerStats (
      name VARCHAR(50) NOT NULL,
      year INT NOT NULL,
      teamID INT NOT NULL,
      PRIMARY KEY(name, year, teamID),
      pos VARCHAR(50),
      age INT,
      G INT,
      GS INT,
      MP INT,
      PER INT,
      TS_percent INT,
      PAr3 INT,
      FTr INT,
      ORB_percent INT,
      DRB_percent INT,
      TRB_percent INT,
      AST_percent INT,
      STL_percent INT,
      BLK_percent INT,
      TOV_percent INT,
      USG_percent INT,
      blanl INT,
      OWS INT,
      DWS INT,
      WS INT,
      WS_divide_48 INT,
      blank2 INT,
      OBPM INT,
      DBPM INT,
      BPM INT,
      VORP INT,
      FG INT,
      FGA INT,
      FG_percent INT,
      P3 INT,
      PA3 INT,
      P3_percent INT,
      P2 INT,
      P2A INT,
      P2_percent INT,
      eFG_percent INT,
      FT INT,
      FTA INT,
      FT_percent INT,
      ORB INT,
      DRB INT,
      TRB INT,
      AST INT,
      STL INT,
      BLK INT,
      TOV INT,
      PF INT,
      PTS INT
  );

